#!/bin/bash
if [ $(id -u) -eq 0 ]
then
clear
else
echo -e "Execute o script como usuario \033[1;32mroot\033[0m"
exit
fi
if [ -d /etc/VpsPackdir ]
then
true
else
mkdir /etc/VpsPackdir
fi
if [ -d /etc/VpsPackdir/senha ]
then
true
else
mkdir /etc/VpsPackdir/senha
fi
if [ -d /etc/VpsPackdir/limite ]
then
true
else
mkdir /etc/VpsPackdir/limite
fi

function ConfSquid(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/ConfSquid && bash ConfSquid
}
function limite(){
wget https://raw.githubusercontent.com/ColtSeals/VpsPacket2/master/limite && bash limite
}
function criarusuario(){
wget https://raw.githubusercontent.com/ColtSeals/VpsPacket2/master/criarusuario && bash criarusuario
}
function deletarusuario(){
wget https://raw.githubusercontent.com/ColtSeals/VpsPacket2/master/deletarusuario && bash deletarusuario
}
function redefinirusuario(){
wget https://raw.githubusercontent.com/ColtSeals/VpsPacket2/master/redefinirusuario && bash redefinirusuario
}
function speedtest.py(){
wget https://raw.githubusercontent.com/ColtSeals/VpsPacket2/master/speedtest.py && bash speedtest.py
}
function OpenVPN(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/OpenVPN && bash OpenVPN
}
function RemoverExpirados(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RemoverExpirados && bash RemoverExpirados
}
function Teste(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Teste && bash Teste
}
function BadVpn.sh(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/BadVpn.sh && bash BadVpn.sh
}
function Monitorar(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Monitorar && bash Monitorar
}
function RemoverLimite(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RemoverLimite && bash RemoverLimite
}
function MudarNome(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/MudarNome && bash MudarNome
}
function FirewallBlock(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/FirewallBlock && bash FirewallBlock
}
function FirewallReset(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/FirewallReset && bash FirewallReset
}
function AddHost(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/AddHost && bash AddHost
}
function RemoverHost(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RemoverHost && bash RemoverHost
}
function Backup(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Backup && bash Backup
}
function Restaurar(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Restaurar && bash Restaurar
}
function DetalhesUsuarios(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/DetalhesUsuarios && bash DetalhesUsuarios
}
function Banner(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Banner && bash Banner
}
function LimpadorCache(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/LimpadorCache && bash LimpadorCache
}
function VNC(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/VNC && bash VNC
}
function tcptweaker(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/tcptweaker && bash tcptweaker
}
function DeletarTodos(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/DeletarTodos && bash DeletarTodos
}
function Ajuda(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Ajuda && bash Ajuda
}
function Creditos(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Creditos && bash Creditos
}
function Telegram(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Telegram && bash Telegram
}
function Desinstalar(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Desinstalar && bash Desinstalar
}
function SistemaDetalhes(){
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/SistemaDetalhes && bash SistemaDetalhes 
}
clear
if [[ $1 == "" ]]
then
echo -e "\033[1;37m•••••> © Edited @ColtSeals & TecnologY \033[0m"
echo -e "\033[1;32m•••••> TELEGRAM GRUPO: @NerdologiaVps"
echo -e "\033[1;32m•••••> TELEGRAM CANAL: @VpsNerdologia"
echo -e "\033[1;37mEscolha uma opção:    Para Sair Ctrl + C\033[1;33m
[\033[1;30m01\033[1;33m] Configurar_Squid_SSH \033[1;30m(Squid e openssh configuração)\033[1;33m
[\033[1;30m02\033[1;33m] Limite \033[1;30m(limite de conexoes simultaneas)\033[1;33m
[\033[1;30m03\033[1;33m] Criar_Usuario \033[1;30m(Criar usuarios)\033[1;33m
[\033[1;30m04\033[1;33m] Remover_expirados \033[1;30m(Remover usuarios ja expirados)\033[1;33m
[\033[1;30m05\033[1;33m] Criar_Teste \033[1;30m(Criar usuarios de curta duração)\033[1;33m
[\033[1;30m06\033[1;33m] BadVpn \033[1;30m(Instala badvpn para tunnel udp)\033[1;33m
[\033[1;30m07\033[1;33m] BadVpn_Start \033[1;30m(liberar chamadas voip, jogos online, etc)\033[1;33m
[\033[1;30m08\033[1;33m] BadVpn_Stop \033[1;30m(Parar serviço do badvpn)\033[1;33m
[\033[1;30m09\033[1;33m] Remover_Limite \033[1;30m(Remover limite de conexoes de um usuario)\033[1;33m
[\033[1;30m10\033[1;33m] Mudar_Nome \033[1;30m(Mudar nome de um usuario)\033[1;33m
[\033[1;30m11\033[1;33m] Redefinir_Usuario \033[1;30m(Redefinir Data, senha, etc)\033[1;33m
[\033[1;30m12\033[1;33m] Deletar_Usuario \033[1;30m(Menu Deletar, Desconectar, etc)\033[1;33m
[\033[1;30m13\033[1;33m] Firewall-block \033[1;30m(bloquear torrent, icmp [\033[1;31mRISCOS\033[1;30m])\033[1;33m
[\033[1;30m14\033[1;33m] Reset_Firewall \033[1;30m(Resetar regras iptables [\033[1;31mRISCOS\033[1;30m])\033[1;33m
[\033[1;30m15\033[1;33m] Addhost \033[1;30m(Adicionar Hosts aceitos pelo squid )\033[1;33m
[\033[1;30m16\033[1;33m] Remover_Host \033[1;30m(Remover Hosts aceitos pelo squid)\033[1;33m
[\033[1;30m17\033[1;33m] Monitorar \033[1;30m(Monitorar conexões atuais)\033[0m\033[1;33m
[\033[1;30m18\033[1;33m] Backup-Users \033[1;30m(Backup dos usuarios)\033[1;33m
[\033[1;30m19\033[1;33m] Rest-Users \033[1;30m(Restaurar usuarios feito backup)\033[1;33m
[\033[1;30m20\033[1;33m] Usuarios_Detalhes \033[1;30m(Informacoes sobre os usuarios !!)\033[1;33m
[\033[1;30m21\033[1;33m] Banner \033[1;30m(Adicionar um banner)\033[1;33m
[\033[1;30m22\033[1;33m] Speedtest \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m
[\033[1;30m23\033[1;33m] Sistema_Detalhes \033[1;30m(Detalhes sobre o Sistema)\033[1;33m
[\033[1;30m24\033[1;33m] Deletar_Todos \033[1;30m(Todos os usuarios serão deletados)\033[1;33m
[\033[1;30m25\033[1;33m] Desinstalar \033[1;30m(Remover VpsPack)\033[0m"
read -p ": " opcao
else
opcao=$1
fi
case $opcao in
  1 | 01 )
   ConfSquid;;
  2 | 02 )
   read -p "Usuario: " user
   read -p "Limite: " limite
   limite $user $limite;;
  3 | 03 )
   criarusuario;;
  4 | 04 )
   OpenVPN;;
  5 | 05 )
   RemoverExpirados;;
  6 | 06 )
   Teste;;
  7 | 07 )
   BadVpn.sh;;
  8 | 08 )
   badvpn start;;
  9 | 09 )
   badvpn stop;;
  10)
   Monitorar;; 
  11)
   RemoverLimite;;
  12)
   MudarNome;;
  13)
   RedefinirUsuario;;
  14)
   deletarusuario;;
  15)
   FirewallBlock;;
  16)
   FirewallReset;;
  17)
   AddHost;;
  18)
   RemoverHost;;
  19)
   Backup;;
  20)
   Restaurar;;
  21)
   DetalhesUsuarios;;
  22)
   Banner;;
  23)
   speedtest.py;;
  24)
   LimpadorCache;;
  25)
   VNC;;
  26)
   tcptweaker;;
  27)
   DeletarTodos;;
  28)
   Ajuda;;
  29)
   Creditos;;
  30)
  Telegram;;
  31)
   Desinstalar;;
  32)
   SistemaDetalhes;;
esac
